import { z } from 'zod';

const rawEnvSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']),
  NEXT_PUBLIC_API_BASE_URL: z.string().url(),
  NEXT_PUBLIC_FIREBASE_API_KEY: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: z.string().min(1),
  NEXT_PUBLIC_FIREBASE_APP_ID: z.string().min(1),
  // Connect only when the emulator is configured. Unset means production Firebase.
  NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_URL: z.string().url().optional(),
  NEXT_PUBLIC_FIREBASE_FIRESTORE_EMULATOR_HOST: z.string().min(1).optional(),
  NEXT_PUBLIC_FIREBASE_FIRESTORE_EMULATOR_PORT: z.coerce.number().int().positive().optional(),
  NEXT_PUBLIC_E2E_USER_ID: z.string().min(1).optional(),
  NEXT_PUBLIC_E2E_USER_EMAIL: z.string().email().optional(),
  NEXT_PUBLIC_E2E_USER_NAME: z.string().min(1).optional(),
});

const rawEnv = rawEnvSchema.parse({
  NODE_ENV: process.env.NODE_ENV,
  NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
  NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  NEXT_PUBLIC_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_URL: process.env.NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_URL,
  NEXT_PUBLIC_FIREBASE_FIRESTORE_EMULATOR_HOST: process.env.NEXT_PUBLIC_FIREBASE_FIRESTORE_EMULATOR_HOST,
  NEXT_PUBLIC_FIREBASE_FIRESTORE_EMULATOR_PORT: process.env.NEXT_PUBLIC_FIREBASE_FIRESTORE_EMULATOR_PORT,
  NEXT_PUBLIC_E2E_USER_ID: process.env.NEXT_PUBLIC_E2E_USER_ID,
  NEXT_PUBLIC_E2E_USER_EMAIL: process.env.NEXT_PUBLIC_E2E_USER_EMAIL,
  NEXT_PUBLIC_E2E_USER_NAME: process.env.NEXT_PUBLIC_E2E_USER_NAME,
});

export const env = {
  nodeEnv: rawEnv.NODE_ENV,
  apiBaseUrl: rawEnv.NEXT_PUBLIC_API_BASE_URL,
  firebase: {
    apiKey: rawEnv.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: rawEnv.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: rawEnv.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: rawEnv.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: rawEnv.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: rawEnv.NEXT_PUBLIC_FIREBASE_APP_ID,
    authEmulatorUrl: rawEnv.NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_URL,
    firestoreEmulatorHost: rawEnv.NEXT_PUBLIC_FIREBASE_FIRESTORE_EMULATOR_HOST,
    firestoreEmulatorPort: rawEnv.NEXT_PUBLIC_FIREBASE_FIRESTORE_EMULATOR_PORT,
  },
  e2e: {
    userId: rawEnv.NEXT_PUBLIC_E2E_USER_ID,
    userEmail: rawEnv.NEXT_PUBLIC_E2E_USER_EMAIL,
    userName: rawEnv.NEXT_PUBLIC_E2E_USER_NAME,
  },
} as const;
